/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;


public class App {

    public static void main(String[] args) throws Exception {
    	String db = null;
    	if(args.length != 1) {
    		db = "test";
    	} else {
    		db = args[0];
    	}
    	Class.forName("org.hsqldb.jdbc.JDBCDriver");
    	try(Connection c = DriverManager.getConnection("jdbc:hsqldb:file:"+db, "username", "password")) {
    		try(Statement s = c.createStatement()) {
    			s.execute("CREATE TABLE MY_TABLE(id INT, name VARCHAR(25))");
    		}
    		try(Statement s = c.createStatement()) {
    			s.execute("insert into MY_TABLE(id, name) values (1, 'laci'), (2,'peti'), (3, 'pista')");
    		}
    		try(Statement s = c.createStatement()) {
    			try(ResultSet rs = s.executeQuery("select * from my_table where id > 1")) {
    				while(rs.next()) {
    					System.out.println("id: "+rs.getInt("id")+"\tname: "+rs.getString("name"));
    				}
    			}    			
    		}
    	}
    }
}
