/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

public class App {

	public static void main(String[] args) {
		GroovyDataCreator gdc = new GroovyDataCreator();
		KotlinDataUser kdu = new KotlinDataUser();
		gdc.setFirstId(1);
		gdc.setLastId(10);
		gdc.setRepeateCount(3);
		ScalaDataUser sdu = new ScalaDataUser(
				gdc.create().stream().map(t -> kdu.create(t.getSecond(), t.getFirst())).iterator());
		for (Data d : sdu.javaList().apply(sdu.dataWithId().apply(3))) {
			System.out.println(d.getId() + ": " + d.getName());
		}
	}
}
